// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable enable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260919072100_AddUsersAndSubscriptions")]
    partial class AddUsersAndSubscriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.DnsRecord", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Domain")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<string>("RecordType")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Ttl")
                    .HasColumnType("int");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Value")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("DnsRecords");
            });

            modelBuilder.Entity("Domain.Entities.GamingDomain", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("CustomIp")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Domain")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("GameName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<int>("Priority")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("GamingDomains");
            });

            modelBuilder.Entity("Domain.Entities.ProxyRule", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Destination")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Port")
                    .HasColumnType("int");

                b.Property<int>("Priority")
                    .HasColumnType("int");

                b.Property<string>("Protocol")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("SourcePattern")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("ProxyRules");
            });

            modelBuilder.Entity("Domain.Entities.Subscription", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("EndDate")
                    .HasColumnType("datetime2");

                b.Property<bool>("IsActive")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bit")
                    .HasDefaultValue(true);

                b.Property<string>("RegisteredIp")
                    .HasMaxLength(45)
                    .HasColumnType("nvarchar(45)");

                b.Property<DateTime>("StartDate")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.Property<int>("Type")
                    .HasColumnType("int");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("RegisteredIp");

                b.HasIndex("UserId", "IsActive");

                b.ToTable("Subscriptions");
            });

            modelBuilder.Entity("Domain.Entities.User", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.Property<string>("FirstName")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<long>("TelegramId")
                    .HasColumnType("bigint");

                b.Property<string>("Username")
                    .HasMaxLength(128)
                    .HasColumnType("nvarchar(128)");

                b.HasKey("Id");

                b.HasIndex("TelegramId")
                    .IsUnique();

                b.ToTable("Users");
            });

            modelBuilder.Entity("Domain.Entities.Subscription", b =>
            {
                b.HasOne("Domain.Entities.User", "User")
                    .WithMany("Subscriptions")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

            modelBuilder.Entity("Domain.Entities.User", b =>
            {
                b.Navigation("Subscriptions");
            });
#pragma warning restore 612, 618
        }
    }
}