FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm config set registry https://mirror.abrha.net/repository/npm/ && npm config set strict-ssl false
RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi
COPY . .
RUN npm run build

FROM nginx:alpine AS runtime
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]